"""Fourth migration

Revision ID: de27d4f577f6
Revises: e70a93fb90de
Create Date: 2024-07-11 22:23:49.129966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de27d4f577f6'
down_revision = 'e70a93fb90de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key('fk_post_user_id', 'user', ['user_id'], ['id'])  # Name the foreign key constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_user_id', type_='foreignkey')  # Use the same name for dropping the constraint
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
